--drop table if exists users, categories, events, events_compilations, requests, compilations cascade ;
CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    email   VARCHAR(100) NOT NULL,
            UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          VARCHAR(1000),
    title               VARCHAR(100),
    description         VARCHAR(1000),
    created             TIMESTAMP WITHOUT TIME ZONE,
    dt                  TIMESTAMP WITHOUT TIME ZONE,
    event_lat           REAL,
    event_lon           REAL,
    paid                BOOLEAN,
    participant_max     INT,
    published_dt        TIMESTAMP WITHOUT TIME ZONE,
    request_moderation  BOOLEAN,
    state               VARCHAR(100),
    initiator_id        BIGINT
                        CONSTRAINT events_user
                        REFERENCES users
                        ON UPDATE CASCADE ON DELETE CASCADE,
    category_id         BIGINT
                        CONSTRAINT events_category
                        REFERENCES categories
                        ON UPDATE CASCADE ON DELETE CASCADE,
                        UNIQUE (event_lat, event_lon)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(500),
    pinned  BOOLEAN
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    compilation_id  BIGINT
                    CONSTRAINT events_compilations_comp_id
                    REFERENCES compilations
                    ON UPDATE CASCADE ON DELETE CASCADE,
    event_id        BIGINT
                    CONSTRAINT events_compilations_event_id
                    REFERENCES events
                    ON UPDATE CASCADE ON DELETE CASCADE,
                    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created         TIMESTAMP WITHOUT TIME ZONE,
    event_id        BIGINT
                    CONSTRAINT request_event
                    REFERENCES events
                    ON UPDATE CASCADE ON DELETE CASCADE,
    requester_id    BIGINT
                    CONSTRAINT request_user
                    REFERENCES users
                    ON UPDATE CASCADE ON DELETE CASCADE,
    status          VARCHAR(10),
                    UNIQUE (event_id, requester_id)
);