--drop table if exists users cascade;
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                     name VARCHAR(20) NOT NULL,
                                     email VARCHAR(20) NOT NULL,
                                     UNIQUE (email)
);

